### ISSUE TITLE
How did you do this?

### ISSUE THREAD

**Issue by Pajamaman** [simeonpilgrim/coab#69]
Did you decompile the original game or what?

I'm just curious :)

Edit: aha!

http://simeonpilgrim.com/blog/2005/08/04/curse-of-the-azure-bonds-project/

**Comment by simeonpilgrim** [comment]
Hi. 

I decompiled it to assembly. Then used regex to replace 70k of the 110k lines of assembly. Then i hand translated the rest. As i went i unwound chunks of code like the vga to ega graphics scaling that where not needed and the sound pwm playing.

**Comment by Pajamaman** [comment]
Yes, you described as much in your blog post. Sorry, I should have closed this "issue".

Great work, by the way :)
