### ISSUE TITLE
Why add 1 to stats?

### ISSUE THREAD

**Issue by Pajamaman** [simeonpilgrim/coab#70]
Why does every stat [get an extra point on character creation](https://github.com/simeonpilgrim/coab/blob/master/engine/ovr018.cs#L677)?

```c#
player.stats2.Str.full = Math.Max(player.stats2.Str.full, ovr024.roll_dice(6, 3) + 1);
player.stats2.Int.full = Math.Max(player.stats2.Int.full, ovr024.roll_dice(6, 3) + 1);
player.stats2.Wis.full = Math.Max(player.stats2.Wis.full, ovr024.roll_dice(6, 3) + 1);
player.stats2.Dex.full = Math.Max(player.stats2.Dex.full, ovr024.roll_dice(6, 3) + 1);
player.stats2.Con.full = Math.Max(player.stats2.Con.full, ovr024.roll_dice(6, 3) + 1);
player.stats2.Cha.full = Math.Max(player.stats2.Cha.full, ovr024.roll_dice(6, 3) + 1);
```

At first I thought it was to offset the modular operation but that happens in the `roll_dice` function in ovr024.cs.

**Comment by simeonpilgrim** [comment]
ovr018:15FB		    mov	    al,	3
    ovr018:15FD		    push    ax
    ovr018:15FE		    mov	    al,	6
    ovr018:1600		    push    ax
    ovr018:1601		    call    @roll_dice$q4Word4Word ; roll_dice(Word,Word)
    ovr018:1606		    xor	    ah,	ah
    ovr018:1608		    inc	    ax
    ovr018:1609		    mov	    [bp+stat_value], al

because that's what it does here.

**Comment by simeonpilgrim** [comment]
As to why that was how it was coded, not sure.

**Comment by Pajamaman** [comment]
Internesting...

I have no idea what I'm looking at :+1:

**Comment by simeonpilgrim** [comment]
the values 6 and 3 are used to call roll_dice, and then the results in incremented prior to being inserted into the state_value memory location..

**Comment by Pajamaman** [comment]
Wow, I wouldn't have been able to figure that out. Is this assembly?

**Comment by simeonpilgrim** [comment]
yes, the x86 16 bit asm
